# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9a5c5b06acf03fb2d616b559cc9bca49c92a61a2facddbf596f8b93eeb4484064c0ee4af7c17d5b68d6529f21b64a0f36538c8e43586d04c2ce01e24150de05

test:
  secret_key_base: ffffbdffa56ee233cdf72bc4e159957acaa0a68c369f1ce9284d4cefb4b064916bac7bc876d75eb8c500869301b6e18fb515fc13dea84560cd5eb75623013e4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
